from datetime import timezone
from os import getenv


TIMEZONE = timezone.utc

DISCORD_TOKEN = getenv("DISCORD_TOKEN", "")
DISCORD_GUILD_ID = int(getenv("DISCORD_GUILD_ID", "0"))
DISCORD_ADMIN_ROLE_ID = int(getenv("DISCORD_ADMIN_ROLE_ID", "0"))
DISCORD_NOTIFICATIONS_CHANNEL_ID = int(getenv("DISCORD_NOTIFICATIONS_CHANNEL_ID", "0"))
DISCORD_MESSAGES_CHANNEL_ID = int(getenv("DISCORD_MESSAGES_CHANNEL_ID", "0"))
DISCORD_MUSIC_CHANNEL_ID = int(getenv("DISCORD_MUSIC_CHANNEL_ID", "0"))

PORTAINER_API_URL = getenv("PORTAINER_API_URL", "")
PORTAINER_API_KEY = getenv("PORTAINER_API_KEY", "")
PORTAINER_MANAGER_NODE_ENDPOINT_ID = int(getenv("PORTAINER_MANAGER_NODE_ENDPOINT_ID", "0"))
PORTAINER_HEAVY_NODE_ENDPOINT_ID = int(getenv("PORTAINER_HEAVY_NODE_ENDPOINT_ID", "0"))

TURN_ON_HEAVY_NODE_CONTAINER_NAME = getenv("TURN_ON_HEAVY_NODE_CONTAINER_NAME", "turn-on-cluster-heavy-node-0")
TURN_OFF_HEAVY_NODE_CONTAINER_NAME = getenv("TURN_OFF_HEAVY_NODE_CONTAINER_NAME", "turn-off-cluster-heavy-node-0")
MINECRAFT_CONTAINER_NAME = getenv("MINECRAFT_CONTAINER_NAME", "minecraft-minecraft-1")

MINECRAFT_DOMAIN_NAME = getenv("MINECRAFT_DOMAIN_NAME", "localhost")
MINECRAFT_PASSWORD = getenv("MINECRAFT_PASSWORD", "")
